language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  # - "2.6"
  # - "pypy"

env:
  - "DB=mysql DB_VERSION=5.5"
  - "DB=mysql DB_VERSION=5.6"
  - "DB=mariadb DB_VERSION=5.5"
  - "DB=mariadb DB_VERSION=10.0"
  - "DB=mariadb DB_VERSION=10.1"

before_script: .travis/before_script.sh

install: pip install -r requirements.txt

script: ./runtests.py
