sudo: required

language: python

env:
  - "DB=mysql DB_VERSION=5.5"
  - "DB=mysql DB_VERSION=5.6"
  # apt repo seems to be broken
  # - "DB=mariadb DB_VERSION=5.5"
  - "DB=mariadb DB_VERSION=10.0"
  - "DB=mariadb DB_VERSION=10.1"

before_script: .travis/before_script.sh

install:
  - pip install coveralls tox

script:
  - coverage erase
  - tox -- -v 2

after_success:
  - coverage combine
  - coveralls
